### ISSUE TITLE
安装环境运行报错

### ISSUE THREAD

**Issue by lzkgbld** [ZSAIm/VideoCrawlerEngine#1]
使用的系统是centos7.64位，Python版本3.6.8。
已经按照文档要求先使用pip install -r requirements.txt安装相关环境，但是最后Python mian.py的时候报错。
  File "main.py", line 2, in <module>
    from script import init_scripts
  File "/home/VideoCrawlerEngine-master/script/__init__.py", line 5, in <module>
    from utils import utility_package, split_name_version
  File "/home/VideoCrawlerEngine-master/utils.py", line 12, in <module>
    from debugger import dbg
  File "/home/VideoCrawlerEngine-master/debugger.py", line 3, in <module>
    from contextvars import ContextVar
ModuleNotFoundError: No module named 'contextvars'

**Comment by MatrixFour** [comment]
contextvars包安装错误，你可以用匹配手动安装一下，使用pip install contextvars, 或者使用pip install contextvars=XXX，其中的XXX代表包的版本，可以从requirements.txt中看到。

**Comment by MatrixFour** [comment]
> 使用的系统是centos7.64位，Python版本3.6.8。
> 已经按照文档要求先使用pip install -r requirements.txt安装相关环境，但是最后Python mian.py的时候报错。
> File "main.py", line 2, in
> from script import init_scripts
> File "/home/VideoCrawlerEngine-master/script/**init**.py", line 5, in
> from utils import utility_package, split_name_version
> File "/home/VideoCrawlerEngine-master/utils.py", line 12, in
> from debugger import dbg
> File "/home/VideoCrawlerEngine-master/debugger.py", line 3, in
> from contextvars import ContextVar
> ModuleNotFoundError: No module named 'contextvars'

contextvars包安装错误，你可以用匹配手动安装一下，使用pip install contextvars, 或者使用pip install contextvars=XXX，其中的XXX代表包的版本，可以从requirements.txt中看到。
