### ISSUE TITLE
使用npm run dev命令报错

### ISSUE THREAD

**Issue by MatrixFour** [ZSAIm/VideoCrawlerEngine#13]
博主，您好！
我在运行您的项目的时候，按照你的要求使用npm run dev或者yarn dev，均产生如下错误：
Error: Cannot find module 'E:\python\VideoCrawlerEngine-master\app\html\build\webpack.dev.conf.js'
Require stack:
- E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack\bin\convert-argv.js
- E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireConfig (E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack\bin\convert-argv.js:97:18)
    at E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack\bin\convert-argv.js:102:15)
    at Object.<anonymous> (E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack-dev-server\bin\webpack-dev-server.js:223:50)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\python\\VideoCrawlerEngine-master\\app\\html\\node_modules\\webpack\\bin\\convert-argv.js',
    'E:\\python\\VideoCrawlerEngine-master\\app\\html\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}

我对前端不是很了解，也尝试解决过这个问题，但是都失败了，请问下这个是项目本身有问题，还是我的环境有问题呢？

**Comment by MatrixFour** [comment]
> 博主，您好！
> 我在运行您的项目的时候，按照你的要求使用npm run dev或者yarn dev，均产生如下错误：
> Error: Cannot find module 'E:\python\VideoCrawlerEngine-master\app\html\build\webpack.dev.conf.js'
> Require stack:
> 
> * E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack\bin\convert-argv.js
> * E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack-dev-server\bin\webpack-dev-server.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>   at Module.require (internal/modules/cjs/loader.js:952:19)
>   at require (internal/modules/cjs/helpers.js:88:18)
>   at requireConfig (E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack\bin\convert-argv.js:97:18)
>   at E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack\bin\convert-argv.js:104:17
>   at Array.forEach ()
>   at module.exports (E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack\bin\convert-argv.js:102:15)
>   at Object. (E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack-dev-server\bin\webpack-dev-server.js:223:50)
>   at Module._compile (internal/modules/cjs/loader.js:1063:30) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   'E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack\bin\convert-argv.js',
>   'E:\python\VideoCrawlerEngine-master\app\html\node_modules\webpack-dev-server\bin\webpack-dev-server.js'
>   ]
>   }
> 
> 我对前端不是很了解，也尝试解决过这个问题，但是都失败了，请问下这个是项目本身有问题，还是我的环境有问题呢？

我仔细检查了您的项目，确实没有build\webpack.dev.conf.js这个文件，不知道是您上传代码的时候误删了，还是我有什么其他的命令没执行

**Comment by ZSAIm** [comment]
嗯，build目录被忽略上传了，待会你重新Pull更新下代码试试。
还有如果你不打算修改前端代码，可以不需要安装前端开发依赖。
