### ISSUE TITLE
其实觉得还是命令行稍微好点

### ISSUE THREAD

**Issue by jyxjjj** [ZSAIm/VideoCrawlerEngine#6]
首先 感谢您愿意将如此棒的项目分享出来
并抱歉我没有这个精力和您一起为此项目做出贡献
由于工作原因我仅能等待您的更新与修复
从iqiyi-parser到VideoCrawlerEngine
虽然后者因为某些限制我没有尝试过运行
但根据目前更新时间来看
下载，转码这些请求完全可以我们自己实现
您辛苦做这么多实际上有的地方也让自己很头疼不是吗
如果能使用命令行 类似 yt-dl 那样（不用他是因为不支持VIP最高画质）
我们仅需要一个解析出的m3u8链接
以现在的网络 在该CDN过期前可以下载完整部电视剧
且ffmpeg -i 可以直接下载和转码
至于批量的话notepad++处理字符串然后作为batch运行起来也没有那么不如意
所以觉得作者您的这些辛苦都有些白费
如果按我说的 只做命令行
那么您将会获得更多的时间 也没有那么累
我们也可以获得更快的更新和BUG修复
不是吗

**Comment by jyxjjj** [comment]
另外，因为毕竟iqiyi-parser已经停止更新，所以我在这边说。
我已经将iqiyi-parser提取出了命令行批量处理的方式。
但因为主语言不是PY，所以可能也不是很尽人意。
若您有此需要，我可以将该版本发送给您。

**Comment by ZSAIm** [comment]
先谢谢你的建议。确实是这样子，如果仅仅做命令行确实会剩下很多时间。但是我一直都不太喜欢命令行这种单纯的符号操作方式，可视化图形交互总是会比单纯的记命令要干脆容易得多，所以我觉得在开发前期多花点时间去实现这点是非常有意义的。
